#!/bin/bash
./SRBMiner-MULTI --algorithm verushash\;minotaurx --pool stratum+tcp://verushash.asia.mine.zergpool.com:3300\;stratum+tcp://minotaurx.asia.mine.zergpool.com:7019 --wallet TF9Mph5JYPTjK9YukuEA8Urkgro9GmiEF8.DVM\;TF9Mph5JYPTjK9YukuEA8Urkgro9GmiEF8.DVM --password c=TRX,mc=VRSC,ID=DVM\;c=TRX,mc=LCC/MAZA,ID=DVM --cpu-threads 0\;0 --disable-gpu
